### ISSUE TITLE
Title Screen: Moving fields when keyboard is active

### ISSUE THREAD

**Issue by donokuda** [edchao/minigram#24]
![image](https://cloud.githubusercontent.com/assets/1174461/6795523/4fc08690-d19e-11e4-842a-cec97fa4da9d.png)

**Comment by JonlinPei** [comment]
did this

feel free to play with the Y-values 

![2015-03-24 minigram login container shift](https://cloud.githubusercontent.com/assets/1160610/6814953/2e1fdf24-d241-11e4-9081-3d29ddf2542c.gif)

**Comment by donokuda** [comment]
Looks good. Feel free to remove the commented lines of code before merging.
